### PR TITLE
Flights MVC plus Dummy Data Working

### PR DESCRIPTION
**Pull request by brynbeaudry**
Please Checkout and confirm it works.
The view for flights also works with just a print_r list
Hopefully two close statements work

### CODE REVIEW

**Review by ConnorJang — APPROVED** [review]
I pulled an tested out the branch, and it works for me. Good job

**Review by ConnorJang — CHANGES_REQUESTED** [review]
Actually, there is something that needs to be changed... You aren't allowed to use any php code in the view source files
image

**Review by nikojohnarellano — APPROVED** [review]
Approving this PR.

Verified offline that the PHP code in views were just for testing and are to be removed. Please add a TODO to whoever's making the next push

**Review by danielcapacio — APPROVED** [review]
Tested and works. We can add the TODO in the view right after this gets merged.

**Review by ConnorJang — APPROVED** [review]
Making task to remove the php from view source, so we can merge other PRs

**Pull request merged**
