### PR TITLE
Flightschedules/data

### PR DESCRIPTION
**Pull request by brynbeaudry**
The data requirements 👍 

It's randomly generated so feel free to test

each airport in your "network" is visited at least twice a day. √
each of three planes making a two return trips to one your "network" destinations √

no departures before 08:00 √
no landings after 22:00 √
minimum 30 minutes between a plane's landing and any subsequent departure √
all of your fleet must be back at your airline base by the end of the day √

flight times need to be reasonable, based on distance between airports, airplane cruising speed, 
√ googled the real flight times

and a 10 minute buffer added to each flight in order to reach cruising/landing speed and altitude
√ usually left 30 minute room for error

### CODE REVIEW

**Review by danielcapacio — COMMENTED** [review]
Tested and looked over data. All the requirements are met, except sometimes I'm getting landings after 22:00 - which goes against a restriction.

Other than that - looks great.

**Comment by danielcapacio** [comment]
See above comment.
landing-exceeds-2200

**Comment by nikojohnarellano** [comment]
@brynbeaudry  seems like some flight schedules still doesnt meet the criteria. can you please fix this.

**Comment by brynbeaudry** [comment]
Thanks for letting me know. Appearantly without a relative timestamp for today, strtotime will use the current time, at tomorrows date for some reason. Although tomorrows date is probably fine, the times are now set correctly, relative to 12am. So when I say +8 hours, it will always be +8 hours from 12am
image

**Review by nikojohnarellano — APPROVED** [review]
Issue is fixed. Great job Bryn, flights data looks neat!

**Review by danielcapacio — APPROVED** [review]
Sweet, data looks good! Awesome!

**Pull request merged**
